[obzvon]

exten => 1256,1,Answer()									; автообзвон разовый через скрипт с Asterisk для отдела кадров и МИМ
    same => n,Set(CHANNEL(accountcode)=${zakaz})
    same => n,Set(CDR(realdst)=${number})
    same => n,Playback(${razg})
    same => n(hang),Hangup()
